# -*- coding: utf-8 -*-
"""credit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Se5I6Owua9vcGdB8U1hLVl4TwDds24TP
"""

# Credit Risk Assessment - Final Professional Version

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Load dataset
data = pd.read_csv("/content/german_credit_data.csv")

# 2. Handle missing values
data.fillna("Unknown", inplace=True)

# 3. Encode categorical columns
le = LabelEncoder()
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le.fit_transform(data[col])

# 4. Separate features and target
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# 5. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# 6. Feature scaling (IMPORTANT)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 7. Train model
model = LogisticRegression(max_iter=2000)
model.fit(X_train, y_train)

# 8. Predictions
y_pred = model.predict(X_test)

# 9. Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# 10. Predict new applicant safely
new_applicant = pd.DataFrame(X.mean()).T
new_applicant = scaler.transform(new_applicant)

prediction = model.predict(new_applicant)
print("\nCredit Risk Prediction:",
      "Good (Loan Approved)" if prediction[0] == 1 else "Bad (Loan Rejected)")